### ISSUE TITLE
QR Codes can be scanned on phone via deep link but not via QR code scan on app

### ISSUE THREAD

**Issue by alexfigtree** [openwallet-foundation-labs/learner-credential-wallet#622] opened 2024-06-18 19:56 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://claim.dcconsortium.org/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjljMjFjNjc4OWRkMWY0MjZkODk5ZiIsImlhdCI6MTcxODIwNzA3MywiZXhwIjoxNzE5NDE2NjczfQ.SDw1iWgNaIIBfuCDf0KEg_TufwiGWJ7VnkbbO3kk21g

2. Scan via phone camera (works)
2. Scan via QR code on app (works)

**Expected behavior**
Should work in both scenarios

**Screenshots**

**Comment by kayaelle** [comment] 2024-09-03 17:03
Recommend we shift from medium to priority.

**Comment by kayaelle** [comment] 2024-12-04 19:40
@alexfigtree - I think this is a dupe of #627

**Closed** 2024-12-05 14:51 UTC
Labels: bug, medium
